# tap "romkatv/powerlevel10k"
# brew "chezmoi"
brew "gh"
brew "git"
brew "jq"
# brew "zoxide"
# brew "fzf"
# brew "eza"
# brew "fd"
# brew "neovim"
# brew "zsh-syntax-highlighting"
# brew "zsh-autosuggestions"
# brew "zsh-completions"
# brew "mise"
# brew "powerlevel10k"
# brew "ripgrep"
# brew "bat"
brew "tree"

# cask "font-dejavu-sans-mono-nerd-font"
# cask "font-source-han-code-jp"
cask "ghostty"
cask "google-chrome"
# cask "karabiner-elements" # USキーボードの場合
# cask "raycast"
# cask "slack"
# cask "visual-studio-code"
cask "zed"
